FROM openjdk:8

WORKDIR /app/jhipster-project

ADD /build/libs/j-hipster-0.0.1-SNAPSHOT.war /app/jhipster-project

MAINTAINER brennan.c.belew@vanderbilt.edu

EXPOSE 8080 

CMD java -jar j-hipster-0.0.1-SNAPSHOT.war --spring.profiles.active=dev,swagger